#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#   Switched to postgres for heroku TM
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: blograilstonymaseda_development

test: &test
  <<: *default
  database: blograilstonymaseda_test

production:
  <<: *default
  database: blograilstonymaseda_production
  username: blograilstonymaseda
  password: <%= ENV['BLOGRAILSTONYMASEDA_DATABASE_PASSWORD'] %>

cucumber:
  <<: *test
